#!/usr/bin/env python3
"""council_signer.py — Standalone off-box council signing utility.

Run by a council member on a LOCAL, AIR-GAPPED machine. It has NO dependency on
Pocket OS and makes NO network calls. Its job is narrow and fail-closed:

  1. Take the canonical ratification payload the member is being asked to sign.
  2. PRINT the exact canonical JSON bytes that will be committed to the ledger,
     so the member can verify what they are signing BEFORE signing.
  3. Produce the HMAC-SHA256 signature under the member's private key.
  4. Print a JSON object the member can paste into `/ratify` as one entry of
     the `signatures` map.

The signature is generated by the member's key on the member's machine and
never touches Pocket OS until submitted for verification. Pocket OS holds only
verification keys; it cannot forge a member's signature.

Usage (production / air-gapped):

    # Inspect what you are being asked to sign (no key needed):
    python3 council_signer.py --candidate D-MEM-1001 --state RATIFIED \
        --member council-a --show-payload

    # Produce a signature (key read from a file or env, NOT argv/ps):
    python3 council_signer.py --candidate D-MEM-1001 --state RATIFIED \
        --member council-a --key-file ./council-a.key

    # Or read the key from an environment variable:
    COUNCIL_KEY_HEX=... python3 council_signer.py --candidate D-MEM-1001 \
        --state RATIFIED --member council-a --key-env COUNCIL_KEY_HEX

All output to stderr is commentary; the final JSON signature goes to stdout so
it can be piped/captured cleanly. With --verify-inspect you may validate an
existing signature against a public verification key without holding the
private key.

Exit codes: 0 on success, 1 on any misuse, 2 on verification failure.
"""

from __future__ import annotations

import argparse
import hashlib
import hmac
import json
import os
import sys

# Must match council_ratification.ALLOWED_STATES exactly.
ALLOWED_STATES = frozenset({"RATIFIED", "PROMOTED"})
# The state Pocket OS ratifies decisions INTO.
RATIFIED_STATE = "RATIFIED"


def canonical(candidate_id: str, state: str, ratifier: str) -> str:
    """Deterministic signed payload — MUST byte-match council_ratification.py."""
    return json.dumps(
        {"candidate_id": candidate_id, "ratifier": ratifier, "state": state},
        sort_keys=True,
        separators=(",", ":"),
    )


def sign(candidate_id: str, state: str, ratifier: str, key: bytes) -> str:
    """HMAC-SHA256 over the canonical payload."""
    return hmac.new(key, canonical(candidate_id, state, ratifier).encode(),
                    hashlib.sha256).hexdigest()


def verify(candidate_id: str, state: str, ratifier: str, signature: str,
           key: bytes) -> bool:
    """Constant-time check of a signature against a verification key."""
    expected = sign(candidate_id, state, ratifier, key)
    return hmac.compare_digest(expected, signature)


def _read_key_file(path: str) -> bytes:
    """Read a hex or raw-bytes key file. Fails closed on any malformed input."""
    try:
        with open(path, "rb") as fh:
            data = fh.read().strip()
    except OSError as exc:
        print(f"error: cannot read key file '{path}': {exc}", file=sys.stderr)
        sys.exit(1)
    return _parse_key_bytes(data, source=f"file {path}")


def _read_key_env(name: str) -> bytes:
    raw = os.environ.get(name)
    if raw is None:
        print(f"error: environment variable '{name}' is not set", file=sys.stderr)
        sys.exit(1)
    return _parse_key_bytes(raw.encode(), source=f"env {name}")


def _parse_key_bytes(data: bytes, source: str) -> bytes:
    """Accept 64 hex chars (32 bytes) or raw 32 bytes. Reject everything else."""
    text = data.decode().strip()
    # 64 hex chars -> 32 raw bytes
    if len(text) == 64:
        try:
            return bytes.fromhex(text)
        except ValueError:
            pass
    # raw 32 bytes
    if len(data) == 32:
        return data
    print(f"error: key from {source} must be 32 bytes (64 hex chars or raw); "
          f"got {len(data)} bytes", file=sys.stderr)
    sys.exit(1)


def _validate(candidate_id: str, state: str, member: str) -> None:
    if not candidate_id:
        print("error: --candidate is required", file=sys.stderr)
        sys.exit(1)
    if state not in ALLOWED_STATES:
        print(f"error: state '{state}' is not allowlisted; allowed={sorted(ALLOWED_STATES)}",
              file=sys.stderr)
        sys.exit(1)
    if not member:
        print("error: --member is required", file=sys.stderr)
        sys.exit(1)


def main() -> None:
    ap = argparse.ArgumentParser(
        prog="council_signer",
        description="Off-box council member signing for Pocket OS ratification.")
    ap.add_argument("--candidate", required=True, help="decision/candidate id to sign")
    ap.add_argument("--state", default=RATIFIED_STATE,
                    help=f"target state (default {RATIFIED_STATE})")
    ap.add_argument("--member", required=True, help="council member identity")
    ap.add_argument("--key-file", help="path to a 32-byte key file (hex or raw)")
    ap.add_argument("--key-env", help="name of env var holding a 64-hex key")
    ap.add_argument("--verify-inspect", metavar="HEX_SIGNATURE",
                    help="instead of signing, verify this signature against the "
                         "provided verification key and print PASS/FAIL")
    ap.add_argument("--show-payload", action="store_true",
                    help="print the exact canonical payload to stdout and exit "
                         "(no key required)")

    args = ap.parse_args()
    _validate(args.candidate, args.state, args.member)

    # Show-only mode: print the canonical bytes the member is asked to sign.
    if args.show_payload:
        canon = canonical(args.candidate, args.state, args.member)
        print(canon)
        print(f"# canonical payload above ({len(canon.encode())} bytes) for member "
              f"{args.member}; SHA-256 digest: "
              f"{hashlib.sha256(canon.encode()).hexdigest()}",
              file=sys.stderr)
        return

    # Exactly one key source is required to sign or verify.
    if (args.key_file and args.key_env) or (not args.key_file and not args.key_env):
        print("error: provide exactly one of --key-file or --key-env",
              file=sys.stderr)
        sys.exit(1)
    key = _read_key_file(args.key_file) if args.key_file else _read_key_env(args.key_env)

    # Verification-inspection mode: validate an existing signature.
    if args.verify_inspect:
        ok = verify(args.candidate, args.state, args.member,
                    args.verify_inspect, key)
        print(json.dumps({
            "mode": "verify",
            "member": args.member,
            "candidate_id": args.candidate,
            "state": args.state,
            "signature": args.verify_inspect,
            "result": "PASS" if ok else "FAIL",
        }, indent=2))
        sys.exit(0 if ok else 2)

    # Signing mode.
    canon = canonical(args.candidate, args.state, args.member)
    sig = sign(args.candidate, args.state, args.member, key)
    # Print what was signed to stderr (commentary), the JSON to stdout.
    print(f"# signing canonical payload: {canon}", file=sys.stderr)
    print(json.dumps({
        "mode": "sign",
        "member": args.member,
        "candidate_id": args.candidate,
        "state": args.state,
        "signature": sig,
        "note": "submit this as one entry of the 'signatures' map on /ratify",
    }, indent=2))


if __name__ == "__main__":
    main()
